### ISSUE TITLE
Fluence numpy array is read-only.

### ISSUE THREAD

**Issue by tomelse** [IMSY-DKFZ/simpa#186] opened 2022-10-26 09:45 UTC
I ran [simpa_examples/minimal_optical_simulation.py](https://github.com/IMSY-DKFZ/simpa/blob/main/simpa_examples/minimal_optical_simulation.py) on a fresh simpa install, cloned from the main branch today.

Note, the following parameters were changed from the default example:

```python
SAVE_REFLECTANCE = True
SAVE_PHOTON_DIRECTION = True
```

```python
File /path/to/simpa/core/simulation_modules/optical_simulation_module/optical_forward_model_mcx_reflectance_adapter.py:169, in MCXAdapterReflectance.extract_reflectance_from_fluence(fluence)
    167     ref = fluence[pos] * -1
    168     pos = np.array(pos).T  # reformatting to aggregate results after for multi illuminant geometries
--> 169     fluence[fluence < 0] = 0
    170     return ref, pos, fluence
    171 else:

ValueError: assignment destination is read-only
```

Not sure why the fluence array is read-only. A simple fix would be to just copy fluence with:

```python
fluence = fluence.copy()
```

**Comment by TomTomRixRix** [comment] 2022-11-18 13:56
Thanks for raising this issue. I've just checked it myself and could reproduce it. The `fluence` array seems to be non-writable. When printing `fluence.flags.writable` it returns `False`.

The quick work-around would be to create a copy of the array. I would, however, do this when calling the function and passing the fluence argument.
```python
self.extract_reflectance_from_fluence(fluence=fluence.copy())
```

But perhaps we can find an even better solution. Currently the data is loaded with `jdata`, perhaps we can configure it to load the array in a mutable manner. Or use another method/library for loading the data. Maybe @leoyala knows more about this?

**Comment by leoyala** [comment] 2022-11-23 14:21
Hi @tomelse,

Sorry for the late reply. Could you share more details about your environment? Like your python version, and the output of `pip freeze`, are you using windows or linux? I tried to reproduce the error in my PC but I did not get that error, I get the expected result as in the figure below. 
@TomTomRixRix same information from your side would be great. 

![Figure_1](https://user-images.githubusercontent.com/23067352/203570091-1f04af9c-29d2-4cfc-9e92-1da08223bff0.png)

**Comment by TomTomRixRix** [comment] 2022-11-23 14:34
Oh, that's interesting, so there might be a nice solution if it works in your environment.

I'm on Ubuntu 22.04, using Python 3.10.6 and here are my frozen pip libraries:
[simpa-pip-env-freeze.txt](https://github.com/IMSY-DKFZ/simpa/files/10076409/simpa-pip-env-freeze.txt)

As I already narrowed it down to the `jdata` file loading, it might well be that there was a change in the latest versions.

@leoyala Let me know if you need more information or if I should try running the script with a different dependencies.

**Comment by leoyala** [comment] 2022-11-23 15:10
I tested it now while using `jdata==0.5.1` and with that version, I can reproduce the error. I am more confident now that it is an error coming from the dependencies. 
I have generated an issue with the developers of `jdata` https://github.com/NeuroJSON/pyjdata/issues/4. 
@tomelse and @TomTomRixRix could you try installing `jadata==0.3.7` in your envs and check if that solves your problem?

**Comment by TomTomRixRix** [comment] 2022-11-23 15:17
> I tested it now while using `jdata==0.5.1` and with that version, I can reproduce the error. I am more confident now that it is an error coming from the dependencies. I have generated an issue with the developers of `jdata` [NeuroJSON/pyjdata#4](https://github.com/NeuroJSON/pyjdata/issues/4). @tomelse and @TomTomRixRix could you try installing `jdata==0.3.7` in your envs and check if that solves your problem?

Cool, I've just tested it with `jdata==0.3.7` and it works 🎉 

For now, we could set this specific version of jdata in our dependencies, currently it's `>=0.3.7`, until the issue has been resolved.

**Comment by leoyala** [comment] 2022-11-24 09:33
Qianqian has resolved the issue in `jdata` and the issue is gone for version `0.5.2` so we can update the dependency to `jdata>=0.5.2`. @tomelse will close this issue, feel free to reopen if you still have problems :).

**Closed by leoyala** 2022-11-24 09:33 UTC
